title: Thoughts, Ruminations, & Pontifications
description: Dominic Hopton's personal blog
baseurl: "/ruminations"
url: "https://www.codevoid.net/ruminations"
twitter_username: grork
github_username:  grork

# Build settings
plugins:
  - jekyll-feed
  - jekyll-time-to-read
  - jekyll-seo-tag
  - jekyll-sitemap
  - octopress-minify-html

collections:
  attributions:
    sort_by: position

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"